### ISSUE TITLE
update pip package please~

### ISSUE THREAD

**Issue by cy69855522** [Luolc/AdaBound#16]
Thx for your nice job, but I find that the package doesn't include AdaBoundW, Could you please update it?

**Comment by Luolc** [comment]
I haven't conducted tests on AdaBoundW yet. The tests for an optimizer are quite time-consuming than ordinary engineering code. As it is not a minor change (compared with previous updates), I need a thorough test to make sure it works as we expect before releasing on PyPI.

If you require to use AdaBoundW, you can either clone and setup or just copy the source code now. I believe these two approaches are both easy to take as a workaround.

**Comment by cy69855522** [comment]
Oh, I see. I was in a hurry. I'm sorry
