### ISSUE TITLE
Could you tell me the version of pytorch you use?

### ISSUE THREAD

**Issue by hljjjmssyh** [Luolc/AdaBound#3]

**Comment by chenyangh** [comment]
just check the setup.py:

install_requires=[
          'torch>=0.4.0',
      ],
python_requires='>=3.6.0')

**Comment by Luolc** [comment]
Most experiments tested on 0.4.1.
The optimizer works for >=0.4.0.
I didn't test with earlier versions.

**Comment by Luolc** [comment]
Closed.
