### ISSUE TITLE
Question about the code

### ISSUE THREAD

**Issue by crcrpar** [Luolc/AdaBound#6]
IIRC, because `group['lr']` will never be changed, so `finalr_lr` will always be the same as `group['final_lr']`.
Is this intended?
https://github.com/Luolc/AdaBound/blob/6fa826003f41a57501bde3e2baab1488410fe2da/adabound/adabound.py#L110

**Comment by Luolc** [comment]
As stated in the comment, it was a workaround for lr_scheduler.
If you use an optimizer with a `lr_scheduler`, the values of `group['lr']` would change as time step goes. You may refer to the source code of PyTorch `lr_scheduler` for the detail.

**Comment by crcrpar** [comment]
Thank you very much.
