### ISSUE TITLE
Tensorflow version coming when?

### ISSUE THREAD

**Issue by hiepph** [Luolc/AdaBound#8]
Can't wait to try with Tensorflow. I'm just curious about the release date of Tensorflow version.

**Comment by dingmiaomiao** [comment]
me too

**Comment by RobinFrcd** [comment]
The PyTorch implementation is about 60 lines of code, you guys really can try to do it yourselves.

**Comment by northeastsquare** [comment]
https://github.com/taki0112/AdaBound-Tensorflow

**Comment by hiepph** [comment]
Successfully used Adabound Tensorflow version of `taki0112` as recommended by @northeastsquare. Thanks, will close the issue for now.
